### PR TITLE
Add README

### LINKED ISSUE #3: Add README

### PR DESCRIPTION
**Pull request by fitrisyukriasari**
fixes #3

### CODE REVIEW

**Comment by chashmeetsingh** [comment]
@fitrisyukriasari there is an issue with the images, please check.

**Comment by fitrisyukriasari** [comment]
where is an issue ?

**Comment by chashmeetsingh** [comment]
https://github.com/fitrisyukriasari/TMS_API/blob/master/README.md
Images do not show up

**Comment by fitrisyukriasari** [comment]
ok, i will edit

**Comment by chashmeetsingh** [comment]
I didn't mean to remove those images, I just meant that they aren't showing up so check the images you added once.

**Pull request merged**
